### ISSUE TITLE
Package name toml++

### ISSUE THREAD

**Issue by Rookfighter** [build2-packaging/tomlplusplus#1]
Hi @boris-kolpackov 

I am not quite sure which would be the idiomatic name for the package of this library. The `project` name is clearly `tomlplusplus` as the upstream repo has that name. The include prefix is `toml++` and I think you once told me that target name (i.e. `lib{toml++}`) and include prefix should match. However the namespace when using the library is `toml`. And the library target generated by the upstream build system is called `tomlplusplus`.
For a first shot I just went with `libtoml++` (expecting that the `++` might be troublesome at some point). Now, config options for the package seem to not like the `++` and made me spell the config parameters like `config.libtoml__`. So before renaming again, just wanted to make sure if you have any opinion on this or if there is again a rule of thumb.

**Comment by boris-kolpackov** [comment]
My general approach to resolving such questions is to first look in Debian -- if there is a package for this library, then I pretty much stop thinking any further and just follow their naming. As it turns out, there is a library and it's called `libtomlplusplus`: https://packages.debian.org/bookworm/libtomlplusplus-dev

> The include prefix is toml++ and I think you once told me that target name (i.e. lib{toml++}) and include prefix should match. 

Don't remember saying that but perhaps I did. The general goal here is to have the library name and its include prefix to correspond in order to reduce the chance of libraries ending up with clashing headers. So while it's ideal if the library target name matches include prefix, anything close enough to this is also acceptable.

So to summaries, in this case I would do:

```
libtomlplusplus   -- package name
lib{tomlplusplus} -- library target name
toml++            -- include prefix (also matches how Debian installs it, see https://packages.debian.org/bookworm/amd64/libtomlplusplus-dev/filelist)
```

**Comment by Rookfighter** [comment]
Thanks, I adjusted the naming as you suggested :+1:
